/**
 * Produce a self-contained folder that can be dragged straight into Netlify's
 * "Deploy manually" box — no build step runs on their side.
 *
 * Netlify's Git deploys bundle functions themselves; a manual upload does not,
 * so each function is bundled here with esbuild (exceljs and all other
 * dependencies inlined).
 *
 * Output: netlify-deploy/
 *   index.html                    static test hub
 *   netlify.toml                  routing + runtime settings, no build command
 *   netlify/functions/*.mjs       bundled, dependency-free functions
 */
import { build } from 'esbuild';
import { cp, mkdir, rm, readdir, readFile, stat } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const out = join(root, 'netlify-deploy');

async function dirSize(dir) {
  let total = 0;
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const p = join(dir, entry.name);
    total += entry.isDirectory() ? await dirSize(p) : (await stat(p)).size;
  }
  return total;
}

await rm(out, { recursive: true, force: true });
await mkdir(join(out, 'netlify', 'functions'), { recursive: true });

/**
 * The WebP decoder loads its WebAssembly module with
 * `fs.readFileSync(path.join(__dirname, 'webp.wasm'))`. Bundling moves the code
 * away from that file, so `__dirname` no longer points anywhere useful and the
 * function would throw the first time it met an image. Inlining the binary as
 * base64 keeps the bundle genuinely self-contained.
 */
const inlineWebpWasm = {
  name: 'inline-cwasm-webp',
  setup(builder) {
    builder.onLoad({ filter: /@cwasm[\\/]webp[\\/]index\.js$/ }, async (args) => {
      const source = await readFile(args.path, 'utf8');
      const wasm = await readFile(join(dirname(args.path), 'webp.wasm'));

      // Anchored to the whole line: the call nests parentheses, so a lazy
      // match would leave the outer one dangling and break the syntax.
      const patched = source.replace(
        /^const code = fs\.readFileSync\(.*\)$/m,
        `const code = Buffer.from('${wasm.toString('base64')}', 'base64')`,
      );
      // Fail loudly rather than shipping a bundle that dies on first use.
      if (patched === source) {
        throw new Error('inline-cwasm-webp: the webp.wasm read was not found; the package changed shape.');
      }

      return { contents: patched, loader: 'js' };
    });
  },
};

// 1. Bundle each function into a single dependency-free ES module.
//    The webhook is emitted as `webhook-background.mjs`: the `-background`
//    filename suffix is the one signal Netlify honours even for prebuilt
//    functions, and it is what buys the 15-minute execution window.
const entries = [
  { src: 'webhook', dest: 'webhook-background' },
  { src: 'health', dest: 'health' },
  // Synchronous controller: must NOT be a background function, since it
  // returns the processing result. Bound by Netlify's 60s function limit.
  { src: 'process-order', dest: 'process-order' },
];
for (const { src, dest: name } of entries) {
  await build({
    entryPoints: [join(root, 'netlify', 'functions', `${src}.mts`)],
    outfile: join(out, 'netlify', 'functions', `${name}.mjs`),
    bundle: true,
    platform: 'node',
    format: 'esm',
    target: 'node20',
    minify: false,
    sourcemap: false,
    // Node built-ins stay external; everything else is inlined.
    external: ['node:*'],
    plugins: [inlineWebpWasm],
    banner: {
      // exceljs and friends are CommonJS and expect `require` to exist.
      js: [
        "import { createRequire as __createRequire } from 'node:module';",
        'const require = __createRequire(import.meta.url);',
      ].join('\n'),
    },
    logLevel: 'warning',
  });
  console.log(`bundled netlify/functions/${name}.mjs`);
}

// 2. Static site.
await cp(join(root, 'public'), out, { recursive: true });

// 3. Deploy-time config: no build command, since everything is prebuilt.
const toml = `# Generated by scripts/build-netlify.mjs — do not edit here.
# This folder is already built; Netlify must not try to build it again.
[build]
  publish = "."
  command = ""

[functions]
  directory = "netlify/functions"

# Routing comes from each function's exported config.path
# (/webhook and /health), which the live deploy confirmed Netlify honours
# even for prebuilt functions. No redirects are needed.
`;
await import('node:fs/promises').then((fs) => fs.writeFile(join(out, 'netlify.toml'), toml));

console.log(`\nnetlify-deploy/ ready — ${(await dirSize(out) / 1024 / 1024).toFixed(1)} MB`);
